// Generates src/convert/data/blocks-1.20.1.ts, the list of vanilla 1.20.1 block ids
// used to flag blocks that would load as air.
//
// The output is committed, so this only has to run again if the target version
// changes. It needs the `minecraft-data` package, which is several hundred
// megabytes and so is deliberately not a dependency of the workspace. Install it
// somewhere disposable and point MINECRAFT_DATA at it:
//
//   cd "$(mktemp -d)" && npm init -y >/dev/null && npm install minecraft-data
//   MINECRAFT_DATA="$PWD/node_modules/minecraft-data" \
//     pnpm --filter @smto/mc-schematics gen:blocks
import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';

const location = process.env.MINECRAFT_DATA;
if (!location) {
  console.error('Set MINECRAFT_DATA to the path of an installed minecraft-data package.');
  process.exit(1);
}

const VERSION = '1.20.1';
const require = createRequire(import.meta.url);
const mcData = require(location)(VERSION);
const names = Object.keys(mcData.blocksByName).sort();

const header = `// Generated by scripts/gen-blocks.mjs from minecraft-data. Do not edit by hand.
//
// Every block id that exists in vanilla Minecraft ${VERSION}, used to flag blocks a
// 1.21.11 structure contains that ${VERSION} would load as air. Committed rather than
// computed because it only changes if the target version does.
export const BLOCKS_${VERSION.replaceAll('.', '_')}: readonly string[] = [
`;
const body = names.map((name) => `  'minecraft:${name}',\n`).join('');

writeFileSync(
  new URL('../src/convert/data/blocks-1.20.1.ts', import.meta.url),
  `${header}${body}];\n`,
);
console.log(`wrote ${names.length} block ids`);
